// Code generated by protoc-gen-go. DO NOT EDIT.
// source: mem.proto

package ProtoMessage

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MemTrace_ReadWrite int32

const (
	MemTrace_READ  MemTrace_ReadWrite = 0
	MemTrace_WRITE MemTrace_ReadWrite = 1
)

var MemTrace_ReadWrite_name = map[int32]string{
	0: "READ",
	1: "WRITE",
}
var MemTrace_ReadWrite_value = map[string]int32{
	"READ":  0,
	"WRITE": 1,
}

func (x MemTrace_ReadWrite) Enum() *MemTrace_ReadWrite {
	p := new(MemTrace_ReadWrite)
	*p = x
	return p
}
func (x MemTrace_ReadWrite) String() string {
	return proto.EnumName(MemTrace_ReadWrite_name, int32(x))
}
func (x *MemTrace_ReadWrite) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(MemTrace_ReadWrite_value, data, "MemTrace_ReadWrite")
	if err != nil {
		return err
	}
	*x = MemTrace_ReadWrite(value)
	return nil
}
func (MemTrace_ReadWrite) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_mem_334f2abe266ff17b, []int{0, 0}
}

type MemTrace struct {
	Address              *uint64             `protobuf:"varint,1,req,name=address" json:"address,omitempty"`
	Rw                   *MemTrace_ReadWrite `protobuf:"varint,2,req,name=rw,enum=ProtoMessage.MemTrace_ReadWrite" json:"rw,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *MemTrace) Reset()         { *m = MemTrace{} }
func (m *MemTrace) String() string { return proto.CompactTextString(m) }
func (*MemTrace) ProtoMessage()    {}
func (*MemTrace) Descriptor() ([]byte, []int) {
	return fileDescriptor_mem_334f2abe266ff17b, []int{0}
}
func (m *MemTrace) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MemTrace.Unmarshal(m, b)
}
func (m *MemTrace) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MemTrace.Marshal(b, m, deterministic)
}
func (dst *MemTrace) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MemTrace.Merge(dst, src)
}
func (m *MemTrace) XXX_Size() int {
	return xxx_messageInfo_MemTrace.Size(m)
}
func (m *MemTrace) XXX_DiscardUnknown() {
	xxx_messageInfo_MemTrace.DiscardUnknown(m)
}

var xxx_messageInfo_MemTrace proto.InternalMessageInfo

func (m *MemTrace) GetAddress() uint64 {
	if m != nil && m.Address != nil {
		return *m.Address
	}
	return 0
}

func (m *MemTrace) GetRw() MemTrace_ReadWrite {
	if m != nil && m.Rw != nil {
		return *m.Rw
	}
	return MemTrace_READ
}

func init() {
	proto.RegisterType((*MemTrace)(nil), "ProtoMessage.MemTrace")
	proto.RegisterEnum("ProtoMessage.MemTrace_ReadWrite", MemTrace_ReadWrite_name, MemTrace_ReadWrite_value)
}

func init() { proto.RegisterFile("mem.proto", fileDescriptor_mem_334f2abe266ff17b) }

var fileDescriptor_mem_334f2abe266ff17b = []byte{
	// 140 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcc, 0x4d, 0xcd, 0xd5,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x09, 0x00, 0x51, 0xbe, 0xa9, 0xc5, 0xc5, 0x89, 0xe9,
	0xa9, 0x4a, 0x15, 0x5c, 0x1c, 0xbe, 0xa9, 0xb9, 0x21, 0x45, 0x89, 0xc9, 0xa9, 0x42, 0x12, 0x5c,
	0xec, 0x89, 0x29, 0x29, 0x45, 0xa9, 0xc5, 0xc5, 0x12, 0x8c, 0x0a, 0x4c, 0x1a, 0x2c, 0x41, 0x30,
	0xae, 0x90, 0x01, 0x17, 0x53, 0x51, 0xb9, 0x04, 0x93, 0x02, 0x93, 0x06, 0x9f, 0x91, 0x82, 0x1e,
	0xb2, 0x01, 0x7a, 0x30, 0xdd, 0x7a, 0x41, 0xa9, 0x89, 0x29, 0xe1, 0x45, 0x99, 0x25, 0xa9, 0x41,
	0x4c, 0x45, 0xe5, 0x4a, 0x0a, 0x5c, 0x9c, 0x70, 0x01, 0x21, 0x0e, 0x2e, 0x96, 0x20, 0x57, 0x47,
	0x17, 0x01, 0x06, 0x21, 0x4e, 0x2e, 0xd6, 0xf0, 0x20, 0xcf, 0x10, 0x57, 0x01, 0x46, 0x40, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x47, 0x75, 0xdc, 0x3e, 0x93, 0x00, 0x00, 0x00,
}
