// Code generated by protoc-gen-go. DO NOT EDIT.
// source: mem.proto

package ProtoMessage

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MemTrace_ReadWrite int32

const (
	MemTrace_READ  MemTrace_ReadWrite = 0
	MemTrace_WRITE MemTrace_ReadWrite = 1
)

var MemTrace_ReadWrite_name = map[int32]string{
	0: "READ",
	1: "WRITE",
}
var MemTrace_ReadWrite_value = map[string]int32{
	"READ":  0,
	"WRITE": 1,
}

func (x MemTrace_ReadWrite) Enum() *MemTrace_ReadWrite {
	p := new(MemTrace_ReadWrite)
	*p = x
	return p
}
func (x MemTrace_ReadWrite) String() string {
	return proto.EnumName(MemTrace_ReadWrite_name, int32(x))
}
func (x *MemTrace_ReadWrite) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(MemTrace_ReadWrite_value, data, "MemTrace_ReadWrite")
	if err != nil {
		return err
	}
	*x = MemTrace_ReadWrite(value)
	return nil
}
func (MemTrace_ReadWrite) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_mem_7c5f41fae21c88c8, []int{3, 0}
}

type MemHeader struct {
	TickFrequency        *uint64       `protobuf:"varint,1,req,name=tick_frequency,json=tickFrequency" json:"tick_frequency,omitempty"`
	Timestamp            *uint64       `protobuf:"varint,2,req,name=timestamp" json:"timestamp,omitempty"`
	Cache                *CacheInfo    `protobuf:"bytes,3,req,name=cache" json:"cache,omitempty"`
	MemoryRegion         *MemoryRegion `protobuf:"bytes,4,req,name=memory_region,json=memoryRegion" json:"memory_region,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *MemHeader) Reset()         { *m = MemHeader{} }
func (m *MemHeader) String() string { return proto.CompactTextString(m) }
func (*MemHeader) ProtoMessage()    {}
func (*MemHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_mem_7c5f41fae21c88c8, []int{0}
}
func (m *MemHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MemHeader.Unmarshal(m, b)
}
func (m *MemHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MemHeader.Marshal(b, m, deterministic)
}
func (dst *MemHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MemHeader.Merge(dst, src)
}
func (m *MemHeader) XXX_Size() int {
	return xxx_messageInfo_MemHeader.Size(m)
}
func (m *MemHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_MemHeader.DiscardUnknown(m)
}

var xxx_messageInfo_MemHeader proto.InternalMessageInfo

func (m *MemHeader) GetTickFrequency() uint64 {
	if m != nil && m.TickFrequency != nil {
		return *m.TickFrequency
	}
	return 0
}

func (m *MemHeader) GetTimestamp() uint64 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

func (m *MemHeader) GetCache() *CacheInfo {
	if m != nil {
		return m.Cache
	}
	return nil
}

func (m *MemHeader) GetMemoryRegion() *MemoryRegion {
	if m != nil {
		return m.MemoryRegion
	}
	return nil
}

type CacheInfo struct {
	L1DataSize           *uint64  `protobuf:"varint,1,req,name=l1_data_size,json=l1DataSize" json:"l1_data_size,omitempty"`
	L1InstSize           *uint64  `protobuf:"varint,2,req,name=l1_inst_size,json=l1InstSize" json:"l1_inst_size,omitempty"`
	L2Size               *uint64  `protobuf:"varint,3,req,name=l2_size,json=l2Size" json:"l2_size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CacheInfo) Reset()         { *m = CacheInfo{} }
func (m *CacheInfo) String() string { return proto.CompactTextString(m) }
func (*CacheInfo) ProtoMessage()    {}
func (*CacheInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_mem_7c5f41fae21c88c8, []int{1}
}
func (m *CacheInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CacheInfo.Unmarshal(m, b)
}
func (m *CacheInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CacheInfo.Marshal(b, m, deterministic)
}
func (dst *CacheInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CacheInfo.Merge(dst, src)
}
func (m *CacheInfo) XXX_Size() int {
	return xxx_messageInfo_CacheInfo.Size(m)
}
func (m *CacheInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_CacheInfo.DiscardUnknown(m)
}

var xxx_messageInfo_CacheInfo proto.InternalMessageInfo

func (m *CacheInfo) GetL1DataSize() uint64 {
	if m != nil && m.L1DataSize != nil {
		return *m.L1DataSize
	}
	return 0
}

func (m *CacheInfo) GetL1InstSize() uint64 {
	if m != nil && m.L1InstSize != nil {
		return *m.L1InstSize
	}
	return 0
}

func (m *CacheInfo) GetL2Size() uint64 {
	if m != nil && m.L2Size != nil {
		return *m.L2Size
	}
	return 0
}

type MemoryRegion struct {
	StartAddr            *uint64  `protobuf:"varint,1,req,name=start_addr,json=startAddr" json:"start_addr,omitempty"`
	EndAddr              *uint64  `protobuf:"varint,2,req,name=end_addr,json=endAddr" json:"end_addr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MemoryRegion) Reset()         { *m = MemoryRegion{} }
func (m *MemoryRegion) String() string { return proto.CompactTextString(m) }
func (*MemoryRegion) ProtoMessage()    {}
func (*MemoryRegion) Descriptor() ([]byte, []int) {
	return fileDescriptor_mem_7c5f41fae21c88c8, []int{2}
}
func (m *MemoryRegion) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MemoryRegion.Unmarshal(m, b)
}
func (m *MemoryRegion) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MemoryRegion.Marshal(b, m, deterministic)
}
func (dst *MemoryRegion) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MemoryRegion.Merge(dst, src)
}
func (m *MemoryRegion) XXX_Size() int {
	return xxx_messageInfo_MemoryRegion.Size(m)
}
func (m *MemoryRegion) XXX_DiscardUnknown() {
	xxx_messageInfo_MemoryRegion.DiscardUnknown(m)
}

var xxx_messageInfo_MemoryRegion proto.InternalMessageInfo

func (m *MemoryRegion) GetStartAddr() uint64 {
	if m != nil && m.StartAddr != nil {
		return *m.StartAddr
	}
	return 0
}

func (m *MemoryRegion) GetEndAddr() uint64 {
	if m != nil && m.EndAddr != nil {
		return *m.EndAddr
	}
	return 0
}

type MemTrace struct {
	Address              *uint64             `protobuf:"varint,1,req,name=address" json:"address,omitempty"`
	Rw                   *MemTrace_ReadWrite `protobuf:"varint,2,req,name=rw,enum=ProtoMessage.MemTrace_ReadWrite" json:"rw,omitempty"`
	Cycle                *uint64             `protobuf:"varint,3,req,name=cycle" json:"cycle,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *MemTrace) Reset()         { *m = MemTrace{} }
func (m *MemTrace) String() string { return proto.CompactTextString(m) }
func (*MemTrace) ProtoMessage()    {}
func (*MemTrace) Descriptor() ([]byte, []int) {
	return fileDescriptor_mem_7c5f41fae21c88c8, []int{3}
}
func (m *MemTrace) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MemTrace.Unmarshal(m, b)
}
func (m *MemTrace) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MemTrace.Marshal(b, m, deterministic)
}
func (dst *MemTrace) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MemTrace.Merge(dst, src)
}
func (m *MemTrace) XXX_Size() int {
	return xxx_messageInfo_MemTrace.Size(m)
}
func (m *MemTrace) XXX_DiscardUnknown() {
	xxx_messageInfo_MemTrace.DiscardUnknown(m)
}

var xxx_messageInfo_MemTrace proto.InternalMessageInfo

func (m *MemTrace) GetAddress() uint64 {
	if m != nil && m.Address != nil {
		return *m.Address
	}
	return 0
}

func (m *MemTrace) GetRw() MemTrace_ReadWrite {
	if m != nil && m.Rw != nil {
		return *m.Rw
	}
	return MemTrace_READ
}

func (m *MemTrace) GetCycle() uint64 {
	if m != nil && m.Cycle != nil {
		return *m.Cycle
	}
	return 0
}

func init() {
	proto.RegisterType((*MemHeader)(nil), "ProtoMessage.MemHeader")
	proto.RegisterType((*CacheInfo)(nil), "ProtoMessage.CacheInfo")
	proto.RegisterType((*MemoryRegion)(nil), "ProtoMessage.MemoryRegion")
	proto.RegisterType((*MemTrace)(nil), "ProtoMessage.MemTrace")
	proto.RegisterEnum("ProtoMessage.MemTrace_ReadWrite", MemTrace_ReadWrite_name, MemTrace_ReadWrite_value)
}

func init() { proto.RegisterFile("mem.proto", fileDescriptor_mem_7c5f41fae21c88c8) }

var fileDescriptor_mem_7c5f41fae21c88c8 = []byte{
	// 355 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x90, 0xd1, 0x8a, 0xda, 0x40,
	0x14, 0x86, 0x9b, 0xa8, 0xd5, 0x9c, 0x46, 0x91, 0xa1, 0x60, 0x5a, 0x5a, 0x08, 0x81, 0x82, 0x37,
	0x0d, 0x35, 0x2f, 0x50, 0xa4, 0x5a, 0xf4, 0x22, 0xb0, 0xcc, 0x0a, 0x5e, 0x86, 0x21, 0x73, 0xd4,
	0xb0, 0x99, 0xc4, 0x9d, 0x99, 0x45, 0xf4, 0x21, 0xf6, 0x99, 0xf6, 0xd1, 0x96, 0x4c, 0x12, 0xd7,
	0x65, 0xaf, 0x86, 0xf3, 0xff, 0xdf, 0x7f, 0xce, 0xcf, 0x80, 0x23, 0x50, 0x84, 0x47, 0x59, 0xea,
	0x92, 0xb8, 0x77, 0xd5, 0x13, 0xa3, 0x52, 0x6c, 0x8f, 0xc1, 0x8b, 0x05, 0x4e, 0x8c, 0x62, 0x85,
	0x8c, 0xa3, 0x24, 0xbf, 0x60, 0xa4, 0xb3, 0xf4, 0x21, 0xd9, 0x49, 0x7c, 0x7c, 0xc2, 0x22, 0x3d,
	0x7b, 0x96, 0x6f, 0x4f, 0xbb, 0x74, 0x58, 0xa9, 0xff, 0x5b, 0x91, 0xfc, 0x00, 0x47, 0x67, 0x02,
	0x95, 0x66, 0xe2, 0xe8, 0xd9, 0x86, 0x78, 0x13, 0xc8, 0x6f, 0xe8, 0xa5, 0x2c, 0x3d, 0xa0, 0xd7,
	0xf1, 0xed, 0xe9, 0x97, 0x68, 0x12, 0xde, 0x1e, 0x0c, 0xff, 0x55, 0xd6, 0xba, 0xd8, 0x95, 0xb4,
	0xa6, 0xc8, 0x5f, 0x18, 0x0a, 0x14, 0xa5, 0x3c, 0x27, 0x12, 0xf7, 0x59, 0x59, 0x78, 0x5d, 0x13,
	0xfb, 0xfe, 0x3e, 0x16, 0x1b, 0x84, 0x1a, 0x82, 0xba, 0xe2, 0x66, 0x0a, 0x0e, 0xe0, 0x5c, 0x97,
	0x12, 0x1f, 0xdc, 0x7c, 0x96, 0x70, 0xa6, 0x59, 0xa2, 0xb2, 0x0b, 0x36, 0xfd, 0x21, 0x9f, 0x2d,
	0x98, 0x66, 0xf7, 0xd9, 0x05, 0x1b, 0x22, 0x2b, 0x94, 0xae, 0x09, 0xbb, 0x25, 0xd6, 0x85, 0xd2,
	0x86, 0x98, 0x40, 0x3f, 0x8f, 0x6a, 0xb3, 0x63, 0xcc, 0xcf, 0x79, 0x54, 0x19, 0xc1, 0x0a, 0xdc,
	0xdb, 0x1e, 0xe4, 0x27, 0x80, 0xd2, 0x4c, 0xea, 0x84, 0x71, 0x2e, 0x9b, 0x53, 0x8e, 0x51, 0xe6,
	0x9c, 0x4b, 0xf2, 0x0d, 0x06, 0x58, 0xf0, 0xda, 0xac, 0xaf, 0xf4, 0xb1, 0xe0, 0x95, 0x15, 0x3c,
	0x5b, 0x30, 0x88, 0x51, 0x6c, 0x24, 0x4b, 0x91, 0x78, 0xd0, 0xaf, 0x18, 0x54, 0xaa, 0xd9, 0xd1,
	0x8e, 0xe4, 0x0f, 0xd8, 0xf2, 0x64, 0xb2, 0xa3, 0xc8, 0xff, 0xf0, 0x21, 0x26, 0x1d, 0x52, 0x64,
	0x7c, 0x2b, 0x33, 0x8d, 0xd4, 0x96, 0x27, 0xf2, 0x15, 0x7a, 0xe9, 0x39, 0xcd, 0xdb, 0xe6, 0xf5,
	0x10, 0xf8, 0xe0, 0x5c, 0x31, 0x32, 0x80, 0x2e, 0x5d, 0xce, 0x17, 0xe3, 0x4f, 0xc4, 0x81, 0xde,
	0x96, 0xae, 0x37, 0xcb, 0xb1, 0xf5, 0x1a, 0x00, 0x00, 0xff, 0xff, 0x63, 0xad, 0xa4, 0xf9, 0x21,
	0x02, 0x00, 0x00,
}
