// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package Messages

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Packet struct {
	Tick                 *uint64  `protobuf:"varint,1,req,name=tick" json:"tick,omitempty"`
	Cmd                  *uint32  `protobuf:"varint,2,req,name=cmd" json:"cmd,omitempty"`
	Addr                 *uint64  `protobuf:"varint,3,req,name=addr" json:"addr,omitempty"`
	Size                 *uint32  `protobuf:"varint,4,req,name=size" json:"size,omitempty"`
	Flags                *uint32  `protobuf:"varint,5,opt,name=flags" json:"flags,omitempty"`
	PktId                *uint64  `protobuf:"varint,6,opt,name=pkt_id,json=pktId" json:"pkt_id,omitempty"`
	Pc                   *uint64  `protobuf:"varint,7,opt,name=pc" json:"pc,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Packet) Reset()         { *m = Packet{} }
func (m *Packet) String() string { return proto.CompactTextString(m) }
func (*Packet) ProtoMessage()    {}
func (*Packet) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

func (m *Packet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Packet.Unmarshal(m, b)
}
func (m *Packet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Packet.Marshal(b, m, deterministic)
}
func (m *Packet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Packet.Merge(m, src)
}
func (m *Packet) XXX_Size() int {
	return xxx_messageInfo_Packet.Size(m)
}
func (m *Packet) XXX_DiscardUnknown() {
	xxx_messageInfo_Packet.DiscardUnknown(m)
}

var xxx_messageInfo_Packet proto.InternalMessageInfo

func (m *Packet) GetTick() uint64 {
	if m != nil && m.Tick != nil {
		return *m.Tick
	}
	return 0
}

func (m *Packet) GetCmd() uint32 {
	if m != nil && m.Cmd != nil {
		return *m.Cmd
	}
	return 0
}

func (m *Packet) GetAddr() uint64 {
	if m != nil && m.Addr != nil {
		return *m.Addr
	}
	return 0
}

func (m *Packet) GetSize() uint32 {
	if m != nil && m.Size != nil {
		return *m.Size
	}
	return 0
}

func (m *Packet) GetFlags() uint32 {
	if m != nil && m.Flags != nil {
		return *m.Flags
	}
	return 0
}

func (m *Packet) GetPktId() uint64 {
	if m != nil && m.PktId != nil {
		return *m.PktId
	}
	return 0
}

func (m *Packet) GetPc() uint64 {
	if m != nil && m.Pc != nil {
		return *m.Pc
	}
	return 0
}

type PacketHeader struct {
	ObjId                *string                       `protobuf:"bytes,1,req,name=obj_id,json=objId" json:"obj_id,omitempty"`
	Ver                  *uint32                       `protobuf:"varint,2,opt,name=ver,def=0" json:"ver,omitempty"`
	TickFreq             *uint64                       `protobuf:"varint,3,req,name=tick_freq,json=tickFreq" json:"tick_freq,omitempty"`
	IdStrings            []*PacketHeader_IdStringEntry `protobuf:"bytes,4,rep,name=id_strings,json=idStrings" json:"id_strings,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *PacketHeader) Reset()         { *m = PacketHeader{} }
func (m *PacketHeader) String() string { return proto.CompactTextString(m) }
func (*PacketHeader) ProtoMessage()    {}
func (*PacketHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{1}
}

func (m *PacketHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PacketHeader.Unmarshal(m, b)
}
func (m *PacketHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PacketHeader.Marshal(b, m, deterministic)
}
func (m *PacketHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PacketHeader.Merge(m, src)
}
func (m *PacketHeader) XXX_Size() int {
	return xxx_messageInfo_PacketHeader.Size(m)
}
func (m *PacketHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_PacketHeader.DiscardUnknown(m)
}

var xxx_messageInfo_PacketHeader proto.InternalMessageInfo

const Default_PacketHeader_Ver uint32 = 0

func (m *PacketHeader) GetObjId() string {
	if m != nil && m.ObjId != nil {
		return *m.ObjId
	}
	return ""
}

func (m *PacketHeader) GetVer() uint32 {
	if m != nil && m.Ver != nil {
		return *m.Ver
	}
	return Default_PacketHeader_Ver
}

func (m *PacketHeader) GetTickFreq() uint64 {
	if m != nil && m.TickFreq != nil {
		return *m.TickFreq
	}
	return 0
}

func (m *PacketHeader) GetIdStrings() []*PacketHeader_IdStringEntry {
	if m != nil {
		return m.IdStrings
	}
	return nil
}

// This is supposed to be wire equivalent to the "map" construct supported
// by the proto3 version of the protobuf description syntax. When that
// becomes widely available, this should be converted over to use it.
type PacketHeader_IdStringEntry struct {
	Key                  *uint32  `protobuf:"varint,1,opt,name=key" json:"key,omitempty"`
	Value                *string  `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PacketHeader_IdStringEntry) Reset()         { *m = PacketHeader_IdStringEntry{} }
func (m *PacketHeader_IdStringEntry) String() string { return proto.CompactTextString(m) }
func (*PacketHeader_IdStringEntry) ProtoMessage()    {}
func (*PacketHeader_IdStringEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{1, 0}
}

func (m *PacketHeader_IdStringEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PacketHeader_IdStringEntry.Unmarshal(m, b)
}
func (m *PacketHeader_IdStringEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PacketHeader_IdStringEntry.Marshal(b, m, deterministic)
}
func (m *PacketHeader_IdStringEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PacketHeader_IdStringEntry.Merge(m, src)
}
func (m *PacketHeader_IdStringEntry) XXX_Size() int {
	return xxx_messageInfo_PacketHeader_IdStringEntry.Size(m)
}
func (m *PacketHeader_IdStringEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_PacketHeader_IdStringEntry.DiscardUnknown(m)
}

var xxx_messageInfo_PacketHeader_IdStringEntry proto.InternalMessageInfo

func (m *PacketHeader_IdStringEntry) GetKey() uint32 {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return 0
}

func (m *PacketHeader_IdStringEntry) GetValue() string {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return ""
}

func init() {
	proto.RegisterType((*Packet)(nil), "Messages.Packet")
	proto.RegisterType((*PacketHeader)(nil), "Messages.PacketHeader")
	proto.RegisterType((*PacketHeader_IdStringEntry)(nil), "Messages.PacketHeader.IdStringEntry")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_33c57e4bae7b9afd) }

var fileDescriptor_33c57e4bae7b9afd = []byte{
	// 292 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0xd1, 0x4a, 0xc3, 0x30,
	0x14, 0x86, 0x49, 0xda, 0xce, 0xf5, 0x68, 0x45, 0xa2, 0x42, 0xd0, 0x9b, 0x32, 0xbc, 0xe8, 0x55,
	0x11, 0x6f, 0x04, 0x6f, 0x45, 0xb1, 0x17, 0x82, 0xc4, 0x07, 0x28, 0x59, 0x93, 0x95, 0xac, 0xdb,
	0xda, 0x25, 0x71, 0x30, 0x5f, 0xc3, 0x67, 0xf3, 0x7d, 0xe4, 0xa4, 0x13, 0xf4, 0xee, 0xff, 0xff,
	0xfc, 0xe1, 0x7c, 0xe7, 0x40, 0xb6, 0xd6, 0xce, 0xc9, 0x56, 0x97, 0x83, 0xed, 0x7d, 0xcf, 0xa6,
	0xaf, 0xa3, 0x75, 0xb3, 0x2f, 0x02, 0x93, 0x37, 0xd9, 0x74, 0xda, 0x33, 0x06, 0xb1, 0x37, 0x4d,
	0xc7, 0x49, 0x4e, 0x8b, 0x58, 0x04, 0xcd, 0xce, 0x20, 0x6a, 0xd6, 0x8a, 0xd3, 0x9c, 0x16, 0x99,
	0x40, 0x89, 0x2d, 0xa9, 0x94, 0xe5, 0xd1, 0xd8, 0x42, 0x8d, 0x99, 0x33, 0x9f, 0x9a, 0xc7, 0xa1,
	0x16, 0x34, 0xbb, 0x80, 0x64, 0xb1, 0x92, 0xad, 0xe3, 0x49, 0x4e, 0x8a, 0x4c, 0x8c, 0x86, 0x5d,
	0xc2, 0x64, 0xe8, 0x7c, 0x6d, 0x14, 0x9f, 0xe4, 0xa4, 0x88, 0x45, 0x32, 0x74, 0xbe, 0x52, 0xec,
	0x14, 0xe8, 0xd0, 0xf0, 0xa3, 0x10, 0xd1, 0xa1, 0x99, 0x7d, 0x13, 0x38, 0x19, 0xa9, 0x5e, 0xb4,
	0x54, 0xda, 0xe2, 0xbf, 0x7e, 0xbe, 0xc4, 0x7f, 0x48, 0x97, 0x8a, 0xa4, 0x9f, 0x2f, 0x2b, 0xc5,
	0xce, 0x21, 0xda, 0x69, 0xcb, 0x29, 0x8e, 0x78, 0x20, 0xb7, 0x02, 0x1d, 0xbb, 0x86, 0x14, 0xd9,
	0xeb, 0x85, 0xd5, 0xdb, 0x03, 0xe6, 0x14, 0x83, 0x67, 0xab, 0xb7, 0xec, 0x11, 0xc0, 0xa8, 0xda,
	0x79, 0x6b, 0x36, 0xad, 0xe3, 0x71, 0x1e, 0x15, 0xc7, 0x77, 0x37, 0xe5, 0xef, 0x39, 0xca, 0xbf,
	0x43, 0xcb, 0x4a, 0xbd, 0x87, 0xde, 0xd3, 0xc6, 0xdb, 0xbd, 0x48, 0xcd, 0xc1, 0xba, 0xab, 0x7b,
	0xc8, 0xfe, 0xbd, 0xe1, 0x99, 0x3a, 0xbd, 0xe7, 0x24, 0xac, 0x8a, 0x12, 0xd7, 0xdf, 0xc9, 0xd5,
	0x87, 0x0e, 0x6c, 0xa9, 0x18, 0xcd, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xb7, 0x19, 0x98, 0x50,
	0x87, 0x01, 0x00, 0x00,
}
